# Generated by Django 5.2.4 on 2025-07-05 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websockets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                ("callsign", models.CharField(blank=True, max_length=10)),
                ("ssid", models.IntegerField(default=0)),
                ("passcode", models.IntegerField(default=-1)),
                ("auto_generate_passcode", models.BooleanField(default=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_source", models.CharField(default="manual", max_length=20)),
                ("distance_unit", models.CharField(default="km", max_length=10)),
                ("dark_theme", models.BooleanField(default=False)),
                ("filter_distance_range", models.IntegerField(default=100)),
                ("filter_station_types", models.TextField(blank=True)),
                ("filter_enable_weather", models.BooleanField(default=True)),
                ("filter_enable_messages", models.BooleanField(default=True)),
                ("tnc_settings", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
                "db_table": "user_settings",
            },
        ),
    ]
